// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamBigJson;

#nullable disable

namespace StreamBigJson.Migrations
{
    [DbContext(typeof(PackageIndexContext))]
    [Migration("20250415102956_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("StreamBigJson.Package", b =>
                {
                    b.Property<Guid>("PackageUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "uuid4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "owner");

                    b.HasKey("PackageUuid");

                    b.HasIndex("Name");

                    b.HasIndex("Namespace");

                    b.HasIndex("Namespace", "Name")
                        .IsUnique();

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("StreamBigJson.PackageVersion", b =>
                {
                    b.Property<Guid>("PackageVersionUuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "uuid4");

                    b.Property<Guid?>("PackageUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionNumberString")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "version_number");

                    b.HasKey("PackageVersionUuid");

                    b.HasIndex("PackageUuid");

                    b.ToTable("PackageVersions");

                    b.HasAnnotation("Relational:JsonPropertyName", "versions");
                });

            modelBuilder.Entity("StreamBigJson.PackageVersion", b =>
                {
                    b.HasOne("StreamBigJson.Package", "Package")
                        .WithMany("Versions")
                        .HasForeignKey("PackageUuid");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("StreamBigJson.Package", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
